# config/environments/development.rb
require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Code reloading
  config.enable_reloading = true
  config.eager_load = false

  # Full error reports
  config.consider_all_requests_local = true

  # Caching (disabled in development)
  config.action_controller.perform_caching = false
  config.cache_store = :null_store

  # Error handling
  config.action_dispatch.show_exceptions = :rescuable

  # Print deprecation notices
  config.active_support.deprecation = :log
  config.active_support.disallowed_deprecation = :raise
  config.active_support.disallowed_deprecation_warnings = []

  # Active Record
  config.active_record.migration_error = :page_load
  config.active_record.verbose_query_logs = true
  config.active_record.query_log_tags_enabled = true

  # Action Mailer - use MailHog for email testing
  # MailHog Web UI: http://localhost:8025
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_caching = false
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV.fetch('MAILHOG_HOST', 'localhost'),
    port: ENV.fetch('MAILHOG_PORT', 1025).to_i
  }
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Annotate rendered view with file names
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error on missing translations
  # config.i18n.raise_on_missing_translations = true

  # Apply autocorrection by RuboCop to files generated by rails generate
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
